### PR TITLE
Use a Fragment to host the embed view to fix issues with Compose interop

### PR DESCRIPTION
**Pull request by iujames**
Relates to various discussion in https://github.com/react-native-community/discussions-and-proposals/issues/446

Nesting our view inside of a Fragment is the only way I've found so far to get the desired behavior without destroying the underlying composition when it's removed from the window. This also requires the accompanying Android change https://github.com/appcues/appcues-android-sdk/pull/476

### CODE REVIEW

**Comment by iujames** [comment]
example: an embed targeted to every screen, but the frame only exists on the embeds tab

https://github.com/appcues/appcues-react-native-module/assets/19266448/a913ffed-2c87-4787-87bc-a8182fd952c7

**Comment by iujames** [comment]
example: embed targeted only to screen "Embed Container"


https://github.com/appcues/appcues-react-native-module/assets/19266448/c261edda-a22b-471d-8af6-9fba14fc9adc

**Comment by iujames** [comment]
example: embed targeted only to "Update Profile" (not the tab the frame is on)


https://github.com/appcues/appcues-react-native-module/assets/19266448/aeb5b524-f332-4406-a1d7-13afee2e3715

**Comment by iujames** [comment]
example: three embeds targeted to every screen (using all frames) + another flow on event1


https://github.com/appcues/appcues-react-native-module/assets/19266448/1a386dea-979f-4a9d-b75b-f84237a3471c

**Review by mmaatttt — APPROVED** [review]

**Pull request merged**
